<script setup>
import { computed, ref } from 'vue';

// Choose how a temporary password is issued: generated by the app, or set by
// the System Admin (with Show/Hide so they can check it and note it down).
// v-model: { mode: 'generate' | 'set', password }
const model = defineModel({ type: Object, required: true });
defineProps({ idPrefix: { type: String, default: 'tp' } });
const shown = ref(false);

// Same rule the server enforces for every password.
const problems = computed(() => {
  const pw = model.value.password || '';
  if (model.value.mode !== 'set' || !pw) return [];
  const out = [];
  if (pw.length < 10) out.push('at least 10 characters');
  if (!/[A-Za-z]/.test(pw)) out.push('a letter');
  if (!/\d/.test(pw)) out.push('a number');
  if (pw !== pw.trim()) out.push('no spaces at the start or end');
  return out;
});
const WORDS = ['Frost', 'Court', 'Rebound', 'Pivot', 'Glacier', 'Assist', 'Timber', 'Summit', 'Harbor', 'Baseline', 'Cedar', 'Tipoff'];
function suggest() {
  const r = (n) => crypto.getRandomValues(new Uint32Array(1))[0] % n;
  model.value = { ...model.value, mode: 'set', password: `${WORDS[r(WORDS.length)]}-${1000 + r(9000)}-${WORDS[r(WORDS.length)]}` };
  shown.value = true;
}
const setMode = (mode) => { model.value = { ...model.value, mode }; };
</script>

<template>
  <fieldset>
    <legend class="label">Temporary password</legend>
    <div class="flex flex-wrap gap-x-5 gap-y-1.5 text-sm mb-2">
      <label class="flex items-center gap-2 cursor-pointer">
        <input type="radio" :name="`${idPrefix}-mode`" :checked="model.mode !== 'set'" class="accent-[var(--color-accent)]" @change="setMode('generate')" /> Generate one for me
      </label>
      <label class="flex items-center gap-2 cursor-pointer">
        <input type="radio" :name="`${idPrefix}-mode`" :checked="model.mode === 'set'" class="accent-[var(--color-accent)]" @change="setMode('set')" /> Set it myself
      </label>
    </div>
    <template v-if="model.mode === 'set'">
      <div class="flex gap-2">
        <div class="relative flex-1">
          <input :id="`${idPrefix}-password`" :value="model.password" :type="shown ? 'text' : 'password'" autocomplete="new-password" spellcheck="false"
            class="input pr-16" :aria-describedby="`${idPrefix}-rule`" aria-label="Temporary password"
            @input="model = { ...model, password: $event.target.value }" />
          <button type="button" class="absolute inset-y-0 right-0 px-3 text-xs font-medium text-text-muted hover:text-text"
            :aria-label="shown ? 'Hide password' : 'Show password'" :aria-pressed="shown" @click="shown = !shown">{{ shown ? 'Hide' : 'Show' }}</button>
        </div>
        <button type="button" class="btn btn-secondary shrink-0" @click="suggest">Suggest one</button>
      </div>
      <p :id="`${idPrefix}-rule`" class="text-xs mt-1" :class="problems.length ? 'text-danger font-medium' : 'text-text-muted'">
        {{ problems.length ? `Still needs: ${problems.join(', ')}.` : 'At least 10 characters, with a letter and a number. Use Show to check it and note it down.' }}
      </p>
    </template>
    <p v-else class="text-xs text-text-muted">A readable one (e.g. <em>Cedar-4821-Pivot</em>) is created and shown to you once.</p>
    <p class="text-xs text-text-muted mt-1">They’ll choose their own password the first time they sign in.</p>
  </fieldset>
</template>
